### ISSUE TITLE
Error 'If' object has no attribute 'name'

### ISSUE THREAD

**Issue by qstokkink** [Tribler/mutpy#3]
```
2024-10-30T10:57:23.2802359Z Traceback (most recent call last):
2024-10-30T10:57:23.2803694Z   File "/home/runner/work/tribler/tribler/mutpy/bin/github_report.py", line 131, in <module>
2024-10-30T10:57:23.2804757Z     main()
2024-10-30T10:57:23.2805698Z   File "/home/runner/work/tribler/tribler/mutpy/bin/github_report.py", line 126, in main
2024-10-30T10:57:23.2807086Z     for viewer in run_from_dirs(project_directories, src_dir, test_dir, prefix):
2024-10-30T10:57:23.2808602Z   File "/home/runner/work/tribler/tribler/mutpy/bin/github_report.py", line 99, in run_from_dirs
2024-10-30T10:57:23.2810238Z     yield run(project_dirs, module_name(src_dir, target, prefix), module_name(src_dir, test_file, prefix))
2024-10-30T10:57:23.2812158Z   File "/home/runner/work/tribler/tribler/mutpy/bin/github_report.py", line 84, in run
2024-10-30T10:57:23.2813257Z     mutation_controller.run()
2024-10-30T10:57:23.2814883Z   File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/mutpy/controller.py", line 67, in run
2024-10-30T10:57:23.2816170Z     self.run_mutation_process()
2024-10-30T10:57:23.2817792Z   File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/mutpy/controller.py", line 86, in run_mutation_process
2024-10-30T10:57:23.2819385Z     self.mutate_module(target_module, to_mutate, total_duration)
2024-10-30T10:57:23.2821053Z   File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/mutpy/utils.py", line 304, in __call__
2024-10-30T10:57:23.2822323Z     result = self.method(*args, **kwargs)
2024-10-30T10:57:23.2823809Z   File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/mutpy/controller.py", line 114, in mutate_module
2024-10-30T10:57:23.2825506Z     for mutations, mutant_ast in self.mutant_generator.mutate(target_ast, to_mutate, coverage_injector,
2024-10-30T10:57:23.2827251Z   File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/mutpy/controller.py", line 293, in mutate
2024-10-30T10:57:23.2828797Z     for mutation, mutant in op().mutate(target_ast, to_mutate, self.sampler, coverage_injector, module=module):
2024-10-30T10:57:23.2830492Z   File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/mutpy/operators/base.py", line 36, in mutate
2024-10-30T10:57:23.2831585Z     for new_node in self.visit(node):
2024-10-30T10:57:23.2832856Z   File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/mutpy/operators/base.py", line 66, in visit
2024-10-30T10:57:23.2833992Z     for new_node in self.generic_visit(node):
2024-10-30T10:57:23.2835614Z   File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/mutpy/operators/base.py", line 81, in generic_visit
2024-10-30T10:57:23.2836764Z     for _ in generator:
2024-10-30T10:57:23.2838061Z   File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/mutpy/operators/base.py", line 88, in generic_visit_list
2024-10-30T10:57:23.2839620Z     for new_value in self.visit(value):
2024-10-30T10:57:23.2840841Z   File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/mutpy/operators/base.py", line 66, in visit
2024-10-30T10:57:23.2841967Z     for new_node in self.generic_visit(node):
2024-10-30T10:57:23.2843292Z   File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/mutpy/operators/base.py", line 81, in generic_visit
2024-10-30T10:57:23.2844437Z     for _ in generator:
2024-10-30T10:57:23.2845650Z   File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/mutpy/operators/base.py", line 88, in generic_visit_list
2024-10-30T10:57:23.2846970Z     for new_value in self.visit(value):
2024-10-30T10:57:23.2848174Z   File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/mutpy/operators/base.py", line 66, in visit
2024-10-30T10:57:23.2849301Z     for new_node in self.generic_visit(node):
2024-10-30T10:57:23.2850599Z   File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/mutpy/operators/base.py", line 81, in generic_visit
2024-10-30T10:57:23.2851695Z     for _ in generator:
2024-10-30T10:57:23.2852952Z   File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/mutpy/operators/base.py", line 88, in generic_visit_list
2024-10-30T10:57:23.2854114Z     for new_value in self.visit(value):
2024-10-30T10:57:23.2855305Z   File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/mutpy/operators/base.py", line 54, in visit
2024-10-30T10:57:23.2856361Z     new_node = visitor(node)
2024-10-30T10:57:23.2857704Z   File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/mutpy/operators/inheritance.py", line 120, in mutate_FunctionDef
2024-10-30T10:57:23.2858918Z     if self.is_overridden(node):
2024-10-30T10:57:23.2860365Z   File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/mutpy/operators/inheritance.py", line 18, in is_overridden
2024-10-30T10:57:23.2861585Z     parent_names.append(parent.name)
2024-10-30T10:57:23.2862235Z AttributeError: 'If' object has no attribute 'name'
2024-10-30T10:57:23.4497668Z ##[error]Process completed with exit code 1.
```

**Comment by qstokkink** [comment]
Actually, this also occurs on Python 3.9.
